### ISSUE TITLE
About training landmark model

### ISSUE THREAD

**Issue by prayshe** [davisking/dlib-models#1]
Hi,
Thank you very much for applying the trained landmark model.
I want to use the code supplied by dlib library to train my own model using I-BUG dataset, but I don't know how to convert those pts files to xml which used in the original code. Would you please explain how to train a model like you published here?
I would appreciate any of you answers. Thank U.

**Comment by prayshe** [comment]
By the way, would you mind testing the average normalized error in 300-W dataset just like the original paper? Thank you very much!

**Comment by davisking** [comment]
This example program shows how to train a model: http://dlib.net/train_shape_predictor_ex.cpp.html
