### ISSUE TITLE
Fatal error when trying to detect faces in very small images

### ISSUE THREAD

**Issue by carlosost** [davisking/dlib-models#14]
Hi,

I am using the net_type as you've proposed [here](http://dlib.net/dnn_mmod_face_detection_ex.cpp.html), in conjunction with mmod_human_face_detector.dat, in order to find faces at [this](http://nigos.nist.gov:8080/nist/sd/32/NIST_SD32_MEDS-II_face.zip) data set from NIST.

Everything is perfect, except for one image named small.ppm (width 7 x height 9), that throws the error described bellow:

```
Error detected at line 626
Error detected in file ../dlib/cuda/tensor.h
Error detected in function dlib::alias_tensor_instance dlib::alias_tensor::operator()(dlib::tensor&, size_t) const

Failing expression was offset+size() <= t.size()
offset: 18446744073709551395
size(): 189
```

Well... I compiled dlib using CMAKE without CUDA support (I think so), so I am inclined to believe the problem is really the size of the image and some size limitation of the model.

``cmake .. -DDLIB_USE_CUDA=0``

Is there any lower limit for the image dimensions within the context I tried to describe?

**SO** : CentOS 7
**Language**: C++

**Comment by davisking** [comment]
Right, the image is too small so the downsampling structure of the network
doesn't end up making sense.  You should discard such images.

**Comment by carlosost** [comment]
Perfect! I will do that.

One last question. The error message correlates the problem with some cuda directory. Does it means that the compiling process without CUDA support failed? The cmake command I used should be enough to turn off CUDA support?

Regards.

**Comment by davisking** [comment]
That code is always used no matter what.  It doesn't mean cuda is being used.
