### ISSUE TITLE
shape_predictor_68_face_landmarks parameters used for training?

### ISSUE THREAD

**Issue by Rakeshvcr** [davisking/dlib-models#27]
Hello,
I have a few questions regarding shape_predictor_68_face_landmarks:

1. what was the parameter used for training shape_predictor_68_face_landmarks? In this [Link](https://github.com/davisking/dlib/blob/master/dlib/image_processing/shape_predictor_trainer.h) there is a default parameter, is it the same parameters used or different.
2. How many images were used for training? I trained for 11k images but the accuracy of the model is not good in low light conditions. 

Any suggestion on handling low light conditions.

**Comment by davisking** [comment]
I forget what parameters it was trained with, something like what is suggested in the Kazemi paper. There are notes here http://dlib.net/face_landmark_detection_ex.cpp.html.  Like it says, it's trained on the ibug dataset. The exact one used is http://dlib.net/files/data/ibug_300W_large_face_landmark_dataset.tar.gz
