### ISSUE TITLE
Would you be interested in a pretrainted ResNet50?

### ISSUE THREAD

**Issue by arrufat** [davisking/dlib-models#29]
Over the last week, I trained a ResNet50 on imagenet.
I saved the model with the `bn_con` layers instead of `affine`, so people could use it as a pretrained model to learn other tasks.
I could put it in my own repository, but here it will have more visibility :)

I used the [original code](http://dlib.net/dnn_imagenet_train_ex.cpp.html) of dlib to train the network, but replaced the ResNet34 implementation with my ResNet50 implementation.

Here are the results:

| # crops | top-1 acc | top-5 acc |
|--------:|:----------:|:----------:|
|       1 |    0.77308 |    0.93352 |
|      10 |    0.77426 |    0.93310 |

To put the results into perspective:

- [Original paper](https://arxiv.org/abs/1512.03385) (10 crops)
  - top-1 acc: 0.7926
  - top-5 acc: 0.9475

- [PyTorch Models](https://pytorch.org/docs/stable/torchvision/models.html) (1 crop)
  - top-1 acc: 0.7615
  - top-5 err: 0.9287

- [Keras Applications](https://keras.io/applications/) (unknown crops, but I guess 1)
  - top-1 acc: 0.749
  - top-5 acc: 0.921

So, this implementation gives better results than both PyTorch and Keras.
If you're interested, I will make a PR with the `resnet.h` file that contains all ResNet{18,34,50,101,152}.

**Comment by davisking** [comment]
Sounds like a cool PR to me :)

**Comment by arrufat** [comment]
Cool!
One quick question, should I serialize the model normally?
I've realized that if I do this:

``` c++
std::ofstream fout("resnet50.dnn", std::ios::binary);
std::istringstream sin;
std::ostringstream sout;
dlib::compress_stream::kernel_2a compressor;
dlib::serialize(net, sout);
sin.str(sout.str());
compressor.compress(sin, fout);
```
The model weighs `83,590,760` bytes instead of `91,592,453` bytes.
The issue is that it takes around 13 s to save the model and 10 to load it, but the compression rate achieved is better than using `.bz2`, `.zip`, `.7z` or `.xz` on the raw file.

**Comment by davisking** [comment]
I wouldn't worry about it.  Use a standard method and people will find it less confusing.  `bz2`, `gzip`, or whatever is fine.

**Comment by arrufat** [comment]
Closing as of #30
