### ISSUE TITLE
Computer specs required when training

### ISSUE THREAD

**Issue by Arqenza** [davisking/dlib-models#32]
Thanks for the wonderful library.
I always thank "dlib".

One thing I want you to teach today.
I want to know the computer specs when you trained "dlib_face_recognition_resnet_model_v1.dat".
I especially want to know about memory capacity.

I am trying "dnn_metric_learning_on_images_ex", but the processing is interrupted with "EXCEPTION IN LOADING DATA".
I have 800,000 face images and 2,000 people.
By the way, my computer has 16GB memory and GPU used GTX1070.
I think it is obviously out of memory.

I want to know memory capacity when I trained "dlib_face_recognition_resnet_model_v1.dat" before going to buy a new computer.
Thanks in advance.
Please give me a hint.

**Comment by davisking** [comment]
That error isn't about running out of memory, and that example program prints additional information when it prints that error.  Since you didn't say what it was I have no idea what's happening.  Probably you have corrupted image files on your disk.

**Comment by Arqenza** [comment]
My missing message is "bad allocation".
When I checked the image, Japanese kanji was included in the Exif information.
Adding that image to the johns image data in the sample did not finish the process for a long time.
As soon as all Exif information was deleted, the process was completed successfully.
Thanks to your advice, I do not need to buy a new computer.
Thanks Davis.
