### ISSUE TITLE
Any trained model for ID card shape detector?

### ISSUE THREAD

**Issue by chanduthedev** [davisking/dlib-models#36]
Hi @davisking,

Thank you for the wonderful work.
I would like to know if any trained model for ID card shape detector available? Basically Model should identify Bank Card or National ID card etc or any Card shape. Please let me know if I want to train a new model how to do.
My apologies if it is a basic question.

Thanks in advance.

**Comment by davisking** [comment]
Not that I know of.

**Comment by chanduthedev** [comment]
Noted. Thank you for quick reply @davisking.
