### ISSUE TITLE
Details regarding mmod_human_face_detector

### ISSUE THREAD

**Issue by emial637** [davisking/dlib-models#37]
Hi!

I'm trying to find information about the mmod_human_face_detector model, but I'm having a hard time finding the information I need. 
I'm looking for stuff like network structure and/or some papers describing the method it's based on.
I'm also wondering if it is a regional based CNN with region proposals, or if it is an implementation of YOLO (You Only Look Once).

Is this information available somewhere?

Thanks.

**Comment by emial637** [comment]
I just found:
* https://arxiv.org/pdf/1502.00046.pdf
* http://dlib.net/dnn_mmod_ex.cpp.html

I believe they contain all the information I need.

**Comment by arrufat** [comment]
I think this blog post will also give you a good overview of the method:
http://blog.dlib.net/2017/08/vehicle-detection-with-dlib-195_27.html

**Comment by emial637** [comment]
Yes, thanks. It looks very helpful
