### ISSUE TITLE
What is dlib_face_recognition_resnet_model_v1's format?

### ISSUE THREAD

**Issue by lccro** [davisking/dlib-models#4]
Hi,
I'd like to convert the model dlib_face_recognition_resnet_model_v1.dat to ios' CoreML format.
Apple is kind enough to provide a pip for converting many pre-built formats (caffe, keras, libsvm, sklearn, xgboost) as well as custom ones*.
Could you provide any pointers in how I'd describe the format of dlib_face_recognition_resnet_model_v1.dat?

Any help is much appreciated!

[*] https://apple.github.io/coremltools/coremltools.converters.html

**Comment by davisking** [comment]
Use dlib's net_to_xml() function and look at the outputs.  It dumps the entire network state.
