### ISSUE TITLE
Details about training dnn_age_predictor_v1.dat.bz2

### ISSUE THREAD

**Issue by perets-dev** [davisking/dlib-models#47]
Hi, team, may I ask, you said about dnn_age_predictor_v1.dat.bz2 model: "This model is thus an age predictor leveraging a ResNet-10 architecture", so you just use ResNet-10 architecture (dnn_age_predictor_v1.dat.bz2 model has been trained from scratch, no pretrained weights from other models) or use pretrained ResNet-10 model (transfer learning)?

It would be very good if there are some document, describing the detailed process of training this model and metrics on test dataset.

I ask about that, because ResNet-10 model (description about this model I found here: https://github.com/BVLC/caffe/wiki/Model-Zoo) has been trained on ImageNet. As ImageNet does not allow commercial use, therefore models, which are fitted on this dataset, do not allow commercial use (I am actually not a lawyer, I just think about that like this). But dnn_age_predictor_v1.dat.bz2 model might use ResNet-10 pretrained model and is released under CC0-1.0, which allows commercial use. So, there might be a conflict. (I just think about that like this)

**Comment by davisking** [comment]
It's trained from scratch.  No pretraining.

**Comment by perets-dev** [comment]
Thanks

**Comment by perets-dev** [comment]
Excuse me, davisking, I have edited this question a bit a while ago before you answered to this question (this: https://github.com/davisking/dlib-models/issues/47#issue-1491148893), so, you saw (may be) a previous version of the message. Could you view this question again, thanks) (on github)

**Comment by davisking** [comment]
I don't know anything more about it beyond what is said here https://github.com/davisking/dlib-models#dnn_age_predictor_v1datbz2

**Comment by perets-dev** [comment]
Thanks for the reply
