### ISSUE TITLE
I would like to introduce the facial recognition model I trained, which includes a large number of Asian faces.

### ISSUE THREAD

**Issue by TaguchiModels** [davisking/dlib-models#56]
I have trained a facial recognition model called 'taguchi_face_recognition_resnet_model_v1.dat,' which includes a large number of Asian faces. I would be delighted if it could be added to the dlib library.

[Taguchi models](https://github.com/TaguchiModels/dlibModels/blob/main/README_EN.md)

**Comment by davisking** [comment]
That's awesome.  Send me a PR to add a blurb about it in the README :)

**Comment by TaguchiModels** [comment]
Thank you for merging.
