### ISSUE TITLE
[Query] FDDB dataset and frontal face detector

### ISSUE THREAD

**Issue by vikasguptaiisc** [davisking/dlib-models#8]
Hi @davisking 

Did you use the FDDB dataset for training the HoG based frontal_face_detector? I am aware that the mmod_face_detector doesn't use FDDB.

**Comment by davisking** [comment]
No, I used a dataset I labeled myself (
http://dlib.net/files/data/dlib_face_detector_training_data.tar.gz) and the
images came from the LFW dataset.
